import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 32,
  },
  photoWrapper: {
    position: "relative",
    width: 343,
    height: 240,
    borderRadius: 8,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 16,
  },
  photoButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadText: {
    textAlign: "begin",
    color: "#BDBDBD",
    fontSize: 16,
    marginBottom: 32,
    marginLeft: 20,
  },
  input: {
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    fontSize: 16,
    color: "#212121",
  },
  locationWrapper: {
    position: "relative",
    marginBottom: 32,
    justifyContent: "center",
  },
  locationInput: {
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    paddingVertical: 10,
    paddingLeft: 48,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    fontSize: 16,
    color: "#212121",
  },
  locationIcon: {
    position: "absolute",
    left: 16,
    top: "50%",
    transform: [{ translateY: -12 }],
    zIndex: 1,
  },
  submitButton: {
    backgroundColor: "#F6F6F6",
    paddingVertical: 16,
    borderRadius: 100,
    marginBottom: 16,
  },
  submitButtonText: {
    textAlign: "center",
    color: "#BDBDBD",
    fontSize: 16,
  },
  deleteWrapper: {
    position: "absolute",
    bottom: 32,
    alignSelf: "center",
    width: 70,
    height: 40,
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
});
